version: "3"
services: 
  app:
    build:
      context: ./build/docker
    tty: true
    ports:
      - 1323:1323
    volumes:
      - ./app:/go/src # mount directory
      - ./log:/var/log/es # log directory
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  data: