version: "3"
services: 
  app:
    build:
      context: ./build/docker/app
    tty: true
    ports:
      - 1323:1323
    volumes:
      - ./app:/go/src # working directory
      - ./log:/var/log/es # log directory
    environment:
      TZ: Asia/Tokyo
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: ./build/docker/web
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./web:/usr/src/web # working directory
    environment:
      - WATCHPACK_POLLING=true # enable hot reload
      - TZ=Asia/Tokyo

volumes:
  data: